version: '2'
services:
    web:
      restart: always
      build: ./webpage
      hostname: produccion
      volumes:
        - /usr/src/app
        - /usr/src/app/static
      expose:
        - "8000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro  
      env_file: ./webpage/.env
      command: /usr/local/bin/gunicorn network_lab.wsgi:application -w 2 -b :8000

    nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      volumes:
        - /www/static
      volumes_from:
        - web

    mysql:
      image: mysql:latest
      volumes:
        - /var/lib/mysql
      expose:
        - "3306"
      environment:
        MYSQL_DATABASE: mysql
        MYSQL_USER: mysql
        MYSQL_PASSWORD: su53RsEc53T!
        MYSQL_ROOT_PASSWORD: secret

#networks:
#  default:
#    external:
#      name: uchuva-net
