 # This file defines two services, the db service and web service
 version: '2'
 services:
   postgres:
     restart: always 
     image: postgres
     volumes:
       - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     expose:
       - "5432"

   web: 
     hostname: production
     restart: always 
     build: ./webpage
     command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn page.wsgi -b 0.0.0.0:8000"
     volumes: # map the current directory with a new webpage directory into the container (like share directories)
       - ./webpage:/webpage
     expose:
       - "8000"
     links:
       - postgres:postgres
     env_file: containers_environment_variables # add the variables defined on this file into the container enviroment variables
 
   nginx:
     restart: always
     image: 192.168.28.50:5000/nginx
     #build: ./nginx
     ports: 
       - "80:80"
     volumes_from:
       - web
     links:
       - web:web