# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
version: '2'
services:
    web:
      restart: always
      image: 192.168.28.50:5000/lascilab/web
      hostname: produccion
      volumes:
        - /usr/src/app
        - /usr/src/app/static
      expose:
        - "8000"
      env_file: ./webpage/.env
      command: /usr/local/bin/gunicorn network_lab.wsgi:application -w 2 -b :8000

    git:
      restart: always
      image: 192.168.28.50:5000/lascilab/wiki
      volumes:
        - /srv/html
      expose:
        - "3000"

    nginx:
      restart: always
      image: 192.168.28.50:5000/lascilab/nginx
      ports:
        - "80:80"
      volumes:
        - /www/static
      volumes_from:
        - web
        - git
#      environment:
#        - "constraint:node: "=frontend01"
#        - "affinity:container==*kubelet*"
#        - "affinity:container!=*proxy*"

    mysql:
      image: 192.168.28.50:5000/mysql:latest
      restart: always
      volumes:
        - /var/lib/mysql
      expose:
        - "3306"
      environment:
        MYSQL_DATABASE: mysql
        MYSQL_USER: mysql
        MYSQL_PASSWORD: su53RsEc53T!
        MYSQL_ROOT_PASSWORD: secret

#networks:
#  default:
#    external:
#      name: uchuva-net
