 # This file defines two services, the db service and web service
 version: '2'
 services:
   postgres:
     restart: always 
     image: postgres
     env_file: containers_environment_variables
     volumes:
       - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     expose:
       - "5432"

   git:
      restart: always
      build: ./wiki
      volumes:
        - /srv/html
      expose:
        - "3000"

   web: 
     hostname: production
     restart: always 
     build: ./webpage
     command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn page.wsgi -b 0.0.0.0:8000"
     volumes: 
       - ./webpage:/webpage
     expose:
       - "8000"
     links:
       - postgres:postgres
     env_file: containers_environment_variables
 
   nginx:
     restart: always
     build: ./nginx
     ports: 
       - "80:80"
     volumes_from:
       - web
     links:
       - web:web
     volumes:
       - /www/static
     volumes_from:
       - web
       - git
